### PR TITLE
Update plugins for the latest advisory

### PR DESCRIPTION
**Pull request by batmat**

### CODE REVIEW

**Review by alecharp — COMMENTED** [review]
LGTM but merge conflicts..

**Review by alecharp — APPROVED** [review]

**Comment by batmat** [comment]
:man_facepalming: fixed. Thanks Adrien

**Review by alecharp — APPROVED** [review]

**Comment by rtyler** [comment]
Ahck, I totally forgot about this.

**Comment by rtyler** [comment]
ci.jenkins.io, and in turn the GitHub Branch Source plugin [don't believe this pull request has a Jenkinsfile](https://gist.github.com/rtyler/2da07b3837271e8efbef8a71ef512e90).

:angry:

**Comment by rtyler** [comment]
One more time with feeling

**Pull request merged**
