### PR TITLE
Update to latest weekly / handle remotingCLI symbol removal

### PR DESCRIPTION
**Pull request by batmat**
Shows https://github.com/jenkinsci/evergreen-plugin/pull/20 in use

### CODE REVIEW

**Comment by batmat** [comment]
First commit is just a starting point, showing that 2.165 will fail if done alone.

**Comment by batmat** [comment]
Will cleanup the PR on Evergreen-plugin before merge, the code is not clean and documented enough, but the concept was proved to work.

**Comment by rtyler** [comment]
@batmat the tests are all passing, is this still a WIP?

**Comment by batmat** [comment]
@rtyler given you fixed the test afaiu, let's go ahead.

However I'm very AFK. I think it would be good to spawn a new instance now **before** merging to check the update actually works fine. WDYT ?

**Comment by batmat** [comment]
Have an instance running locally the current UL. 
image

Will check if it updates fine to upcoming UL190

**Comment by batmat** [comment]
yey 
image

**Pull request merged**
