### PR TITLE
Disable DNS multicast for Jenkins instances

### PR DESCRIPTION
**Pull request by rtyler**
Related to [JENKINS-33596](https://issues.jenkins-ci.org/browse/JENKINS-33596)

### CODE REVIEW

**Comment by rtyler** [comment]
Unfortunately jenkinsci/jenkins#2301 got stalled out with an exploded scope, so we'll have to suffer with this for now.

**Comment by batmat** [comment]
This seems OK, but you say it relates to https://issues.jenkins-ci.org/browse/JENKINS-53477. I'm sorry but I fail to see the link. I would expect us to embed in commit logs such reasons BTW, so that future code archeology is made _a bit_ simpler.

**Comment by rtyler** [comment]
Whoops, totally linked the wrong ticket: https://issues.jenkins-ci.org/browse/JENKINS-33596

**Comment by batmat** [comment]
BTW, this is another example of things that users will need to pull the latest image to benefit from.

**Pull request merged**
