### PR TITLE
[JENKINS-59287] Fix README instructions for IPv6

### PR DESCRIPTION
**Pull request by candrews**

### CODE REVIEW

**Comment by jsoref** [comment]
I think I'd like the commit message to explain that `ident.me` may return an ipv4 or ipv6 address but that this command expects an ipv4 address so the change is to provide the input it's expecting.

With that, this seems like a perfectly reasonable change.

**Comment by candrews** [comment]
> I think I'd like the commit message to explain that `ident.me` may return an ipv4 or ipv6 address but that this command expects an ipv4 address so the change is to provide the input it's expecting.

Sounds good to me - I've updated this PR accordingly.

**Comment by jsoref** [comment]
> However, this command expects an ipv4 address so this change provides the input (and ipv4 address) it's expecting.

Definitely better, do you mean `and ipv4` or `an ipv4`?

**Comment by candrews** [comment]
> Definitely better, do you mean `and ipv4` or `an ipv4`?

:man_facepalming: 

Updated the PR.

**Comment by jsoref** [comment]
Oh, I'd probably change the PR summary, something like:

> Fix README instructions to not fail if user has an IPv6 address

(It took me a couple of readings to understand why one would be providing an IPv4 address as the change for a PR that was talking about IPv6)

Sorry for the small input, and thanks for working on IPv6 support.

**Comment by candrews** [comment]
@mandie722 can you please review and (hopefully) merge this one?

**Pull request merged**
