### PR TITLE
Revert "JENKINS-54633 install evergreen in a dedicated VPC"

### PR DESCRIPTION
**Pull request by batmat**
Reverts jenkins-infra/evergreen#352

### CODE REVIEW

**Comment by imod** [comment]
please see my comment at https://github.com/jenkins-infra/evergreen/pull/352#issuecomment-470833329

**Comment by batmat** [comment]
No time to dig into it. AFAIU something still is broken, despite it shouldn't. [Jesse hit this issue yesterday too](https://issues.jenkins-ci.org/browse/JENKINS-57317?focusedCommentId=368740&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-368740), so effectively as it is now, it prevents people from using Evergreen on AWS easily.

Hence I'm going to fix this user issue by reverting this, and I'll be happy to review in the future a new PR for this, which this time I'll actually test... Sorry about that.

**Review by rtyler — APPROVED** [review]

**Comment by rtyler** [comment]
Punting CI

**Comment by rtyler** [comment]
Oof, because this is an origin branch, the pr-merge status isn't going to be filed. :face_with_head_bandage:

**Pull request merged**
